version: '3.9'

services:  
  mssql:    
    container_name: adventure-works-2022-sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1439:1433"
    environment:
      MSSQL_PID: "Developer"
      MSSQL_LCID: "1036"
      MSSQL_SA_PASSWORD: "Sc63ym23!!"
      ACCEPT_EULA: "Y" 
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
      - ./scripts:/var/opt/mssql/scripts

volumes:
  cache:
    driver: local
  data:
    driver: local
  backup:
    driver: local
  scripts:
    driver: local